apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Grafana
  description: Grafana
  annotations:
    grafana/tag-selector: backstage
spec:
  type: website
  lifecycle: production
  owner: user:guest
